development: &default
  adapter: postgresql
  database: gitcasts-website_development
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000
  host: localhost

test:
  <<: *default
  database: gitcasts-website_test
