# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ff9485a55687b63dfbeaa98669ec685eb2b8bf77ce94dae99187d7591379bb4b2e157317585397b6e67a0a37f92e7a63029226a1fc5b70fe9d5247d127bde3b

test:
  secret_key_base: 57886a2ef3cd4f9df31025c5780609322c0be3c9fdcaf320181b09dfc0d40cc1e80186975162bfe4d21c97b4938f72aa113ac4cc1c92177545837f2501959afe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
